### ISSUE TITLE
Wrong redirect on logout

### ISSUE THREAD

**Issue by Unheppcat** [Unheppcat/nor-seasonal-watch-list#3]
Logout redirects the browser to http://, not https://

**Comment by entotto** [comment]
This still appears to be the case (note the value of the Location header starts with `http://`):

<img src="https://user-images.githubusercontent.com/52433044/110431632-e6aa4180-8062-11eb-82db-259391044608.png" width="50%">

I suspect this is because [`request->isSecure()`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/HttpFoundation/Request.php#L1156-L1165) is returning [false when the server is trying to determine](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/HttpFoundation/Request.php#L929-L932) the full URL to redirect to.

The server code does [have provisions to adapt](https://github.com/Unheppcat/nor-seasonal-watch-list/blob/274bdd63d73f7359e880b7ab49b7644c5da7e7f2/application/public/index.php#L22-L27) its relevant setup to [Heroku's environment](https://devcenter.heroku.com/articles/deploying-symfony4#trusting-the-heroku-router). It may be that the `APP_ENV` config var is not set to `prod` on the current Heroku app.

**Comment by entotto** [comment]
^If `APP_ENV` is indeed un/misconfigured, then setting that up might fix #20 and #19 too.

**Comment by Unheppcat** [comment]
APP_ENV was set correctly, but TRUSTED_PROXIES was not. The proxies problem was almost certainly the cause of this bug with the logout redirect. I'm not so certain about the stacktrace issue with #19 and #20. They eventually stopped too, but not after a few more rounds of changes to various environment-related settings.
